### ISSUE TITLE
Account not shown as registered after sms code verification

### ISSUE THREAD

**Issue by Calrama** [WhisperSystems/libtextsecure-java#12]
In developing a [proof-of-concept client](https://github.com/Calrama/TextSecureFX) using  libtextsecure-java according to the steps shown [here](https://open-whisper-systems.readme.io/docs/textsecure-java-library), I was able to successfully register an account using a spare phone. That is (ommitting key generation), I called:
```scala
accountManager.requestSmsVerificationCode()
accountManager.verifyAccount(receivedSmsVerificationCode, generateRandomSignalingKey(), false, generateRandomInstallId())
accountManager.setPreKeys(identityKey.getPublic(), lastResortKey, signedPreKey, oneTimePreKeys);
```
without any errors. Furthermore, I was able to send a message with this new account using this client to my Android phone (different account). However, 
```scala
accountManager.getContact(PHONE_NUMBER)
```
reveals that this new account does not seem to be registered to the server, which is also hinted to by my Android client showing "This message will not be encrypted because the recipient is no longer a TextSecure user. [...]" if I try to write back to the new account.

I seem to be missing something in the registration process, but I am not sure what. Is it necessary to create a device with ```accountManager.addDevice(...)```?

**Comment by moxie0** [comment]
At the moment you'll still need to register a GCM or APN id for your device to be visible.

**Comment by Calrama** [comment]
That would mean there is no way to write a desktop client, since an Android/Apple device is required for GCM/APN?

**Comment by connorlanigan** [comment]
No, you don't need to use the GCM/APN ID. You only have to register any ID, then you can poll messages manually.

**Comment by moxie0** [comment]
That is correct (and the intent).  Although @connorlanigan is correct, you can hack it by registering something bogus.

**Comment by Calrama** [comment]
Thank you both for the information.
@moxie0 Disregarding the reasons for such intent, is this hack something we can rely on, or is it likely to be removed in the future?

**Comment by moxie0** [comment]
@Calrama It could change at any time.  If you're writing a desktop client, the "supported" way is via the device provisioning API.

Your app would display a QR code, an existing TextSecure install would scan that QR code, and then provision your device as being part of an existing account.  The word 'supported' is in quotes there because while that's the right way to do things, libtextsecure-java has been written to handle that flow from the master's perspective rather than the slave's (what you want).

You can check out the TextSecure-Browser repository (the official desktop client in development) to get the full picture.  You might have to fill in one or two missing API calls with raw HTTP requests.

**Comment by Calrama** [comment]
Alright, once again thank you for the explanation, I will look into that.

**Comment by xardazz** [comment]
When using fake GCM id all is ok while you are online. When you go offline after about 10 seconds official client disallows sending  encrypted messages(all messages sent within those 10 secs successfully go to message queue abd can be retrieved on next execution). Is where any workaround?
