### ISSUE TITLE
Using fake GCM id

### ISSUE THREAD

**Issue by xardazz** [WhisperSystems/libtextsecure-java#14]
When using fake GCM id all is ok while you are online. Official clients see you and can send you encrypted messages, but when you go offline after about 10 seconds official client disallows sending encrypted messages(all messages sent within those 10 secs successfully go to message queue abd can be retrieved on next execution). Is where any workaround?

**Comment by Calrama** [comment]
While not a solution to not using GCM, a workaround would be to write a Chrome extension that uses GCM and connect it to your native application though Chrome's NativeMessaging API. That is what I did to deal with this, you can find the code [here](https://github.com/Calrama/GCMN), but it is not production-ready yet. Push message reception works (on Linux) after setting up the NativeMessageHost manually.

**Comment by xardazz** [comment]
I found better solution using AsamK modified lib-textsecure, that allows setting fetchMessages accountFlag to true.

**Comment by Calrama** [comment]
Setting that flag does look like a better option, but considering there is an [open PR about this since April](https://github.com/WhisperSystems/libtextsecure-java/pull/5), I'm not sure about using it. In any case, since you have your solution, you may want to close this.

**Comment by moxie0** [comment]
The correct thing to do is to use the device API. The fetches messages thing will stop working server side shortly.

**Comment by Calrama** [comment]
@moxie0 Since the device API is the correct thing, is there a short example on how to use it? Also, if I understand it correctly, it still requires a master device with GCM/APN, which would make it unusable for people who neither possess such a device (which to me - if indeed so- would an unacceptable exclusion of users).

**Comment by moxie0** [comment]
That's correct, provisioning off a master device is the only supported methodology. The TS chrome app is an example of using it. If that's unacceptable to you, the TS server source is available for you to run however you'd like.

**Comment by Calrama** [comment]
@moxie0 I have through the TS chrome extension and while I personally have no problem going through a certain share of implementation code, I cannot in good conscience consider that to be a sufficient substitute for API documentation (with a minimal example in pseudo-code), especially with regards to the amount of time necessary for other developers wanting to utilise TextSecure APIs. Of course, that is only my opinion and I do know that writing good documentation eats a lot of time.
Also, while I have no problem with modifying the server source and rolling my own in term of work if I truly needed to (which at this point I do not, since I can use a [minimal Chrome extension](https://github.com/Calrama/GCMN), that registers with GCM and pipes notifications to my native desktop application), unless I am mistaken (which is entirely possible), that would mean users registered on the modified server would not be able to communicate through that server with users registered on the official WhisperSystems TextSecure server; this would equal a userbase split orthogonal to the entire point of providing (as-)easy-to-use(-as-possible-without-sacrificing-security), freely available communication encryption. At least in my POV.

**Comment by moxie0** [comment]
That is all correct. The documentation should be better, but there are unfortunately only 24hrs in the day.  In the mean time, if you don't like the choices we've made, you're always free to make your own choices with your own user base.
